### PR TITLE
feat: add practice for ncku mlb course

### PR DESCRIPTION
**Pull request by Allenkooo**
Add some practices for the course

Practice 1 is the practice after finishing 1.  Chain
Practice 2 is the practice after finishing 2.  Data

### CODE REVIEW

**Comment by richarddwang** [comment]
1. typo "define imput templetes" -> "define input templates"

2. Instead of trying to teach both output formatting methods (format via langchain output parser and via openai function), it will be simpler to teach only one of them. (openai function can be better than langchain output parser since the model is finetune for it.)

3. Error

`output = chain.invoke({"article": "穿越你心中夏豔的森林\n樹葉翻飛說些什麼\n你的心...` results in `JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 1 (char 235)`

4. Why it is considered pirating when any of score is larger than 3?

5. Still in progress? Expecting some blanks with comments, better with checks to validate the outputs. The practices can be complex for newbies to complete in an half of an hour.

**Comment by Allenkooo** [comment]
Here are some answers to the question：

1. We will fix this error
2. Okay, we will take only the method to use in homework
3. We will fix this error, this may caused by output of model is not suitable for output parser, but it works sometimes
4. It should be "threshold", not 3
5. Yes, we would like to show you the complete code once to ensure there are no issues before making blanks

We will modify the above problem, and send a new version to you, thanks.

**Review by richarddwang — COMMENTED** [review]
For practice 1:

Feedback:

Nice work! Thank you for taking your time to make such a great contribution.

- The hardness is proper. 

- Well carved blanks.

Suggestions:

1. Translate the "You should how to ..." section into Chinese

2. Introduce `RunnableMap` and `RunnablePassThrough.bind` instead of `RunnableBranch` such that students can understand the LCEL syntaxes used in `1. Chatbot.ipynb`

3. If you want to make the practices more concise and cleaner, maybe we don't need practice output formatting again in the second scenario.

Modifications made:

- Formated code in code cells and markdown cells (black style)

- Inserted space between Chinese characters and English characters

- Changed `to-do` to `TODO` as it comes with syntax highlight in jupyter notebook.

- Revised some descriptions of TODOs

Fixes made:

- `Article` in Practice_1_blank has different attributes and validation function from its answer.

**Comment by richarddwang** [comment]
For practice 2

It is a good way of using embedding similarity to solve pirating detection. And coming up with this should 
take much effort in reading documents and source code, thank you for your hard work.

Although a simple solution t can be more effective for the problem, from the perspective of teaching, there can be some potential issues:

- In the real world, text splitter is not designed to be used to split different articles that combined in a file. It is designed to split a single article into smaller pieces.

- Every time you create a vectorsotre, it calls API to encode texts, which takes money. Usually we don't want to repeat creating the vectorstore.

- Vectorstore is often be used in retrieval to retrieval-augmented generation rather than just computing relevance score.

I 've written an alternative example for pirating detection in a new file `Practice_2_draft.ipynb`, please **format, prettify,  organize, and modify** this draft in the way you think students can understand and learn from the exercises the most. Note that you are free to delete, insert, or edit the contents of the exercise as you want.

**Comment by Allenkooo** [comment]
The teacher has requested that I first make the repository link public, so I will place the link to your repository in the course announcement. 
Additionally, I will make the necessary modifications based on your suggestions and the practice_2, and then push an updated version. Thank you.

**Comment by richarddwang** [comment]
1. Please modify your local version of Practice_1_blank to resolve the confilict.
2. Please push Practice_2_blank before the meeting so I can pull down, review, and revise.

**Comment by richarddwang** [comment]
Looks good to me. Close it.
Note that I have modified Practice2_blank. (as described in another PR).

**Pull request closed without merging**
